# -*- python -*-
from lsst.sconsUtils import env

env.SwigLoadableModule("_cameraGeomLib", ["cameraGeomLib.i"],
                       SWIGFLAGS=(env["SWIGFLAGS"] + ["-DIMPORT_IMAGE_I"]),
                       LIBS=env.getLibs("main python"))

