# -*- python -*-
from lsst.sconsUtils import env

# We can't use BasicSConscript here because the circular dependency requires the -D option in SWIGFLAGS
env.SwigLoadableModule("_cameraGeomLib", ["cameraGeomLib.i"],
                       SWIGFLAGS=(env["SWIGFLAGS"] + ["-DIMPORT_IMAGE_I"]),
                       LIBS=env.getLibs("main python"))

