## -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11(
    ['image/image',
     'apCorrMap/apCorrMap',
     'calib',
     'color',
     'coaddInputs',
     'filter',
     'photoCalib',
     'exposure/exposure',
     'exposureInfo',
     'maskedImage/maskedImage',
     'imageUtils',
     'imageSlice',
     'readMetadata',
     'imagePca',
     'transmissionCurve',
     'visitInfo',
     'defect'],
    addUnderscore=False
)
