# -*- python -*-
from lsst.sconsUtils import env

env.SwigLoadableModule("_imageLib", ["imageLib.i"], SWIGFLAGS=(env["SWIGFLAGS"] + ["-DIMPORT_FUNCTION_I"]),
                       LIBS=env.getLibs("main python"))
