# -*- python -*-
import re
Import("env")

env.CheckSwig("python", ilang="c++", includedProducts="utils daf_base pex_exceptions pex_logging pex_policy daf_persistence daf_data security ndarray afw")
env.LoadableModuleIncomplete("_xpa", ["xpa.i"],
                             CCFLAGS=re.sub("-Wall", "", " ".join(env['CCFLAGS'])),
                             LIBS = ["xpa"] + env.getlibs("pex_exceptions"))
env.LoadableModuleIncomplete("_displayLib", Split("displayLib.i simpleFits.cc"),
                             CCFLAGS=re.sub("-Wall", "", " ".join(env['CCFLAGS'])),
                             LIBS=env.getlibs("afw"))
