# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11(
    ['rgb', "_simpleFits"],
    extraSrc={"rgb": ["saturated.cc", "scaling.cc"],
              "_simpleFits": ["simpleFits.cc"]},
)
