# -*- python -*-
Import("env")

env.CheckSwig("python", ilang="c++", includedProducts="utils daf_base pex_exceptions pex_logging pex_policy daf_persistence daf_data security afw")
env.LoadableModuleIncomplete("_xpa", ["xpa.i"], LIBS = ["xpa"] + env.getlibs("pex_exceptions"))
env.LoadableModuleIncomplete("_displayLib", Split("displayLib.i simpleFits.cc"), LIBS=env.getlibs("afw"))
