from lsst.sconsUtils import env, targets

ptenv = env.Clone()


# gcc supposed to take the last in case of ambiguity
# For clarity, remove existing optimization flags

for x in ('-O1','-O2','-O3'):
    if x in ptenv['CCFLAGS']:
        ptenv['CCFLAGS'].remove(x)

ptenv.AppendUnique(CCFLAGS=[ '-pthread', '-Og'])

# Tell SCons the program to build
targets['examples'].extend( 
  ptenv.Program('ptest', ['ptest.cc'] , LIBS = env.getLibs("main"))
)
