# -*- python -*-
import os

from lsst.sconsUtils import scripts, env, targets

afwdataDir = env.ProductDir("afwdata")

pybind11_ported_tests = ['tests/testFunctor.py',
                         'tests/testGeomTestUtils.py',
                         'tests/testSeparableXYTransform.py',
                         'tests/testXYTransform.py',
                         'tests/testAngle.py',
                         'tests/testBox.py',
                         'tests/testCoord.py',
                         'tests/testCoordinates.py',
                         'tests/testFunction.py',
                         'tests/testSpatialCell.py',
                         'tests/testSpline.py',
                         'tests/testMinimize.py',
                         'tests/testGaussianProcess.py',
                         'tests/testInterpolate.py']

if not afwdataDir:
	testArgs = dict(statistics = "--run_test=!StatisticsTestImages", background = "--run_test=!BackgroundTestImages",)
	scripts.BasicSConscript.tests(pyList=pybind11_ported_tests, args=testArgs)
else:
	# copy AFWDATA_DIR to the test's environment
	env["ENV"]["AFWDATA_DIR"] = afwdataDir
	scripts.BasicSConscript.tests(pyList=pybind11_ported_tests)

env.Clean(targets["tests"], "#testTable.fits")
