# -*- python -*-
Import("env")

env.CheckSwig("python", ilang="c++", includedProducts="utils daf_base pex_exceptions pex_logging pex_policy daf_persistence daf_data security afw")
env.LoadableModuleIncomplete("_detectionLib", Split("detectionLib.i"), LIBS=env.getlibs("afw"))

