# -*- python -*-
Import("env")
import os

env.CheckSwig("python", ilang="c++")
env['SWIGFLAGS'] += " -I%s" % (os.path.join(os.environ["MWI_DIR"], "python"))
env.LoadableModuleIncomplete("_xpa", ["xpa.i"], LIBS = ["xpa"])
env.LoadableModuleIncomplete("_fwDisplay", Split("fwDisplay.i simpleFits.cc"),
                             LIBS=env.libs["vw"] + env.libs["fits"] + ["fw"] + ["wcs"])
#env.LoadableModuleIncomplete("_test", ["test.i"])
