# -*- python -*-
Import("env")

env.CheckSwig("python", ilang="c++")
env.LoadableModuleIncomplete("_xpa", ["xpa.i"], LIBS = ["xpa"])
env.LoadableModuleIncomplete("_fwDisplay", Split("fwDisplay.i simpleFits.cc"),
                             LIBS=env.libs["vw"] + env.libs["fits"] + ["fw"])
#env.LoadableModuleIncomplete("_test", ["test.i"])
