# -*- python -*-
Import("env")

env.CheckSwig("python", ilang="c++")
env.LoadableModuleIncomplete("_xpa", ["xpa.i"], LIBS = ["xpa"])
env.LoadableModuleIncomplete("_fwLib", Split("fwLib.i simpleFits.cc"),
                             LIBS=env.libs["vw"] + env.libs["fits"])
#env.LoadableModuleIncomplete("_test", ["test.i"])
