# -*- python -*-
Import("env")

env.CheckSwig("python", ilang="c++", includedProducts="utils daf_base")
env.LoadableModuleIncomplete("_detectionLib", Split("detectionLib.i"), LIBS=env.getlibs("afw"))

