# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11(
    [
        'detail/frameSetUtils',
        'wcsUtils/wcsUtils',
        'sipApproximation',
        'span',
        'spanSet',
        'endpoint',
        'transform/transform',
        'transformFactory',
        'skyWcs/skyWcs',
    ],
    addUnderscore=False
)
