# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11([
    'affineTransform',
    'angle',
    'box',
    'coordinateBase',
    'coordinateExpr',
    'extent',
    'functor',
    'point',
    'spherePoint',
    'separableXYTransform',
    'span',
    'spanSet',
    'linearTransform',
    'xYTransform',
])
