# -*- python -*-
Import("env")

env.CheckSwig("python", ilang="c++", includedProducts="afw pex_exceptions utils daf_base pex_logging pex_policy daf_persistence daf_data security")
env.LoadableModuleIncomplete("_coordLib", Split("coordLib.i"), LIBS=env.getlibs("afw"))
