include ../etc/Makefile.global

all :
	@: no default actions

install :
	@ mkdir -p $(ETCDIR)
	cp Makefile.global makedefs installdefs $(ETCDIR)

clean:
	$(RM) *~ core*

distclean: clean
	@: nothing extra to do
