# -*- python -*-
Import('env')

if False:
    print "TURN DOXY BACK ON"
else:
    doxy = env.Doxygen("htmlDir", "doxygen.conf")
    moduleList = ("display","detection","image","geom","math","eigen")
    for module in moduleList:
        env.Ignore(doxy, Glob("../python/lsst/afw/%s/*_wrap.cc" % module))
        env.Ignore(doxy, Glob("../python/lsst/afw/%s/*.py" % module))
        env.Depends(doxy, "../include/lsst/afw/%s.h" % module)
    env.Depends(doxy, "../include/lsst/afw/image/ImageExceptions.h")
    #env.AlwaysBuild(doxy)
