// -*- lsst-c++ -*-
#ifndef AFW_TABLE_Simple_h_INCLUDED
#define AFW_TABLE_Simple_h_INCLUDED

#include "lsst/afw/table/RecordInterface.h"
#include "lsst/afw/table/TableInterface.h"

namespace lsst { namespace afw { namespace table {

class SimpleRecord;
class SimpleTable;

/// @brief A tag class for SimpleTable and SimpleRecord to be used with the interface classes.
struct Simple {
    typedef SimpleRecord Record;
    typedef SimpleTable Table;
};

/**
 *  @brief A bare-bones record class intended for testing and generic tabular data.
 */
class SimpleRecord : public RecordInterface<Simple> {
private:

    friend class detail::Access;

    SimpleRecord(RecordBase const & other) : RecordInterface<Simple>(other) {}
};

/**
 *  @brief A bare-bones record class intended for testing and generic tabular data.
 */
class SimpleTable : public TableInterface<Simple> {
public:

    /**
     *  @brief Construct a new table.
     *
     *  @param[in] schema            Schema that defines the fields, offsets, and record size for the table.
     *  @param[in] capacity          Number of records to pre-allocate space for in the first block.  This
     *                               overrides nRecordsPerBlock for the first block and the first block only.
     *  @param[in] idFactory         Factory class to generate record IDs when they are not explicitly given.
     *                               If empty, defaults to a simple counter that starts at 1.
     */
    SimpleTable(
        Schema const & schema,
        int capacity = 0,
        PTR(IdFactory) const & idFactory = PTR(IdFactory)()
    ) : TableInterface<Simple>(schema, capacity, idFactory) {}

    /// @brief Create a table from a base-class table.  Required to implement RecordBase::getTable().
    explicit SimpleTable(TableBase const & base) : TableInterface<Simple>(base) {}
    
    /// @brief Create and add a new record with an ID generated by the table's IdFactory.
    Record addRecord() const { return _addRecord(); }

    /// @brief Create and add a new record with an explicit RecordId.
    Record addRecord(RecordId id) const { return _addRecord(id); }

    /**
     *  @brief Write a FITS binary table.
     *
     *  @param[in]   filename        Name of the FITS file to open.  This will be passed directly
     *                               to cfitsio, so all of its extended filename syntaxes should
     *                               work here.
     *  @param[in]   sanitizeNames   If true, periods in names will be converted to underscores.
     */
    void writeFits(std::string const & filename, bool sanitizeNames=true);

    /**
     *  @brief Load a table from a FITS binary table.
     *
     *  @param[in]   filename        Name of the FITS file to open.  This will be passed directly
     *                               to cfitsio, so all of its extended filename syntaxes should
     *                               work here.
     *  @param[in]   unsanitizeNames If true, underscores in names will be converted to periods.
     */
    static SimpleTable readFits(std::string const & filename, bool unsanitizeNames=true);

};

}}} // namespace lsst::afw::table

#endif // !AFW_TABLE_Simple_h_INCLUDED
