# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11(['_detection',
                                  'peak/peak',
                                  'gaussianPsf',
                                  'heavyFootprint'],
                                 # Need .cc here or Scons will look for the wrong file type
                                 extraSrc={'_detection': ['_psf.cc',
                                                          '_footprintCtrl.cc',
                                                          '_footprint.cc',
                                                          '_threshold.cc',
                                                          '_footprintSet.cc',
                                                          '_footprintMerge.cc',
                                                          ],
                                           'peak/peak': [],
                                           'gaussianPsf': [],
                                           'heavyFootprint': [],
                                           },
                                 addUnderscore=False)
