# -*- python -*-
import glob, os, re

Import('env')
#
# Here's a way to to build the files in the list noOptFiles without optimisation
#

ccFiles = glob.glob("../src/*/*.cc") + glob.glob("../src/*/*/*.cc") + glob.glob("../src/*/*/*/*.cc")

# link with GPU code
import eups
if eups.productDir("cuda_toolkit") and eups.productDir("cuda_sdk"):
    ccFiles.append('../src/math/detail/convGPU.os')

try:
    ccFiles = env.SourcesForSharedLibrary(ccFiles)
except AttributeError:                  # requires sconsUtils > 3.3
    pass

env.SharedLibrary(
    'afw', ccFiles, LIBS=[x for x in env.getlibs("afw") if x != "afw"]
)
