# -*- python -*-
import re
Import("env")

env.CheckSwig("python", ilang="c++",
    includedProducts="utils daf_base pex_exceptions pex_logging pex_policy daf_persistence daf_data security afw")
env.LoadableModuleIncomplete("_mathLib", Split("mathLib.i"),
                             CCFLAGS=re.sub("-Wall", "", " ".join(env['CCFLAGS'])),
                             LIBS=env.getlibs("afw"))
