from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11(['function',
                                  'functionLibrary',
                                  'minimize',
                                  'interpolate',
                                  'gaussianProcess',
                                  'spatialCell',
                                  'boundedField',
                                  'chebyshevBoundedField',
                                  'leastSquares',
                                  'random',
                                  'convolveImage',
                                  'statistics',
                                  'stack',
                                  'kernel'])

