# -*- python -*-
import glob, sys
Import('env')

env.Program(["Image.cc"], LIBS=env.getlibs("afw"))
env.Program(["Image_1.cc"], LIBS=env.getlibs("afw"))
env.Program(["Image_2.cc"], LIBS=env.getlibs("afw"))
env.Program(["Mask.cc"], LIBS=env.getlibs("afw"))
env.Program(["DecoratedImage.cc"], LIBS=env.getlibs("afw"))
env.Program(["MaskedImage.cc"], LIBS=env.getlibs("afw"))
env.Program(["Statistics.cc"], LIBS=env.getlibs("afw"))
env.Program(["MaskedImage_1.cc"], LIBS=env.getlibs("afw"))
env.Program(["MaskedImage_2.cc"], LIBS=env.getlibs("afw"))
env.Program(["FootprintFunctor.cc"], LIBS=env.getlibs("afw"))

env.Program("maskedImageFitsIO", ["maskedImageFitsIO.cc"], LIBS=env.getlibs("afw"))
env.Program("timeImageIterators.cc", LIBS=env.getlibs("afw"))
env.Program("timeImageAddition", ["timeImageAddition.cc"], LIBS=env.getlibs("afw"))
env.Program("timePixelAccess", ["timePixelAccess.cc"], LIBS=env.getlibs("afw"))
env.Program(["timePixelAccessGil.cc"], LIBS=env.getlibs("afw"))

env.Program("chebyshev1Function", ["chebyshev1Function.cc"], LIBS=env.getlibs("afw"))
env.Program("gaussianFunction", ["gaussianFunction.cc"], LIBS=env.getlibs("afw"))
env.Program("integerDeltaFunction", ["integerDeltaFunction.cc"], LIBS=env.getlibs("afw"))
env.Program("lanczosFunction", ["lanczosFunction.cc"], LIBS=env.getlibs("afw"))
env.Program("polynomialFunction", ["polynomialFunction.cc"], LIBS=env.getlibs("afw"))

env.Program(["minimize.cc"], LIBS=env.getlibs("afw"))

env.Program("analyticKernel", ["analyticKernel.cc"], LIBS=env.getlibs("afw"))
env.Program("deltaFunctionKernels", ["deltaFunctionKernels.cc"], LIBS=env.getlibs("afw"))
env.Program("fixedKernel", ["fixedKernel.cc"], LIBS=env.getlibs("afw"))
env.Program("lanczosKernel", ["lanczosKernel.cc"], LIBS=env.getlibs("afw"))

env.Program("convolveLinear", ["convolveLinear.cc"], LIBS=env.getlibs("afw"))
env.Program("simpleConvolve", ["simpleConvolve.cc"], LIBS=env.getlibs("afw"))
env.Program("spatiallyVaryingConvolve", ["spatiallyVaryingConvolve.cc"], LIBS=env.getlibs("afw"))
env.Program("timeConvolve", ["timeConvolve.cc"], LIBS=env.getlibs("afw"))
env.Program("timeSpatiallyVaryingConvolve", ["timeSpatiallyVaryingConvolve.cc"], LIBS=env.getlibs("afw"))

env.Program("makeExposure", ["makeExposure.cc"], LIBS=env.getlibs("afw wcs"))
env.Program("wcsTest", ["wcsTest.cc"], LIBS=env.getlibs("afw wcs"))

env.Program("imageBackground", ["imageBackground.cc"], LIBS=env.getlibs("afw"))
env.Program("imageStatistics", ["imageStatistics.cc"], LIBS=env.getlibs("afw"))
env.Program("splineInterpolate", ["splineInterpolate.cc"], LIBS=env.getlibs("afw"))
env.Program("rombergIntegrate", ["rombergIntegrate.cc"], LIBS=env.getlibs("afw"))
#
# Build all ticket test files
#
for cfile in glob.glob("ticket*.cc"):
    env.Program(cfile, LIBS=env.getlibs("afw"))
