# -*- python -*-
Import('env')

env.Program("sharedPointers", ["sharedPointersExample.cc"], LIBS="citizen")
env.Program(["generate.cc"],
	    LIBS=["citizen"] + env.libs["vw"] + \
            Split("vwMosaic vwImage") + env.libs["boost"])
env.Program(["vwconvert.cc"], LIBS=env.libs["vw"])
env.Program(["fitsio.cc"], LIBS=env.libs["vw"] + env.libs["fits"])
env.Program(["exceptions.cc"])
env.Program("trace", ["traceExample.cc"], LIBS="citizen")
