# -*- python -*-
Import('env')

env.Program("citizen", ["citizen.cc"], LIBS=["fw"] + env.libs["wcs"])
env.Program(["generate.cc"],
	    LIBS=["fw"] + env.libs["wcs"] + env.libs["vw"] + \
            Split("vwMosaic vwImage") + env.libs["boost"])
env.Program(["vwconvert.cc"], LIBS=env.libs["vw"])
env.Program(["fitsio.cc"], LIBS=["fw"] + env.libs["vw"] + env.libs["fits"] + env.libs["wcs"])
env.Program("maskedImageFitsIO", ["maskedImageFitsIO.cc"],
    LIBS=["fw"] + env.libs["vw"] + env.libs["fits"] + ["vwImage"] + env.libs["boost"])
env.Program(["exceptions.cc"], LIBS=["fw"]+ env.libs["wcs"])
env.Program("log", ["log.cc"], LIBS=["fw"]+ env.libs["wcs"])
env.Program("trace", ["trace.cc"], LIBS=["fw"]+ env.libs["wcs"])
#
# Tests
#
import glob, os, sys

import lsst.tests
tests = lsst.tests.Control(env, ignoreList=["fitsio", "generate", "vwconvert"])

if not hasattr(tests, "runExamples"): # before scons 1.16
    try:
        tests.runExamples = (os.stat(tests._tmpDir).st_mode & 0x1) # directory is world executable
    except OSError:
        tests.runExamples = True

if not tests.runExamples:
    print >> sys.stderr, "Not running the examples; \"chmod o+x examples/%s\" to run them" % tests._tmpDir
else:
    print >> sys.stderr, "Running the examples; \"chmod o-x examples/%s\" to not run them" % tests._tmpDir
    tests.run("*.cc")
    tests.run("*.py")
