# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11(
    ["_typehandling"],
    extraSrc={
        "_typehandling": ["_Storable.cc"],
    },
    addUnderscore=False
)
