# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11(
    ['aliasMap/aliasMap',
     'schema/schema',
     'schemaMapper/schemaMapper',
     'base/base',
     'baseColumnView/baseColumnView',
     'arrays/arrays',
     'aggregates/aggregates',
     'slots',
     'simple/simple',
     'source/source',
     'match/match',
     'ampInfo/ampInfo',
     'exposure/exposure',
     'idFactory',
     'wcsUtils',
     ],
    addUnderscore=False,
)
