# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11(
    ['_table',
     'simple/simple',
     'source/source',
     'match/match',
     'ampInfo/ampInfo',
     'exposure/exposure',
     'wcsUtils',
     ],
    extraSrc={
        # Need .cc here or Scons will look for the wrong file type
        '_table': ['_aliasMap.cc',
                   '_schema.cc',
                   '_schemaMapper.cc',
                   '_baseColumnView.cc',
                   '_base.cc',
                   '_idFactory.cc',
                   '_arrays.cc',
                   '_aggregates.cc',
                   '_slots.cc',
                   ],
        'simple/simple': [],
        'source/source': [],
        'match/match': [],
        'ampInfo/ampInfo': [],
        'exposure/exposure': [],
        'wcsUtils': [],
    },
    addUnderscore=False,
)
