include ../etc/Makefile.global

all :
	@: no default actions

install :
	@ mkdir -p $(PYTHONDIR)
	cp fw/__init__.py fits2fic.py $(PYTHONDIR)

clean:
	$(RM) *~ core*

distclean: clean
	@: nothing extra to do
