## -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11(['quadrupole',
                                  'ellipse',
                                  'pixelRegion',
                                  'baseCore',
                                  'axes',
                                  'radii',
                                  'ellipticityBase',
                                  'distortion',
                                  'conformalShear',
                                  'reducedShear',
                                  'separable'])
