# -*- python -*-
Import("env")

env.CheckSwig("python", ilang="c++", includedProducts="utils daf_base pex_exceptions pex_logging pex_policy daf_persistence daf_data security")
env.LoadableModuleIncomplete("_imageLib", Split("imageLib.i"), LIBS=env.getlibs("afw"))
