# Schema for per visit DiaSource tables. Based on the LSST DC2 MySQL DIASource
# schema, modified to allow CORAL to correctly map between database and C++ types.
CREATE TABLE IF NOT EXISTS DiaSourceTemplate
(
    diaSourceId      BIGINT   NOT NULL,
    ampExposureId    BIGINT   NOT NULL,
    filterId         SMALLINT NOT NULL,
    objectId         BIGINT       NULL,
    movingObjectId   BIGINT       NULL,
    scId             INTEGER  NOT NULL,
    colc             DOUBLE   NOT NULL,
    colcErr          FLOAT(0) NOT NULL,
    rowc             DOUBLE   NOT NULL,
    rowcErr          FLOAT(0) NOT NULL,
    dcol             DOUBLE   NOT NULL,
    drow             DOUBLE   NOT NULL,
    ra               DOUBLE   NOT NULL,
    decl             DOUBLE   NOT NULL,
    raErr4detection  DOUBLE   NOT NULL,
    decErr4detection DOUBLE   NOT NULL,
    raErr4wcs        DOUBLE       NULL,
    decErr4wcs       DOUBLE       NULL,
    cx               DOUBLE   NOT NULL,
    cy               DOUBLE   NOT NULL,
    cz               DOUBLE   NOT NULL,
    taiMidPoint      DOUBLE   NOT NULL,
    taiRange         DOUBLE   NOT NULL,
    fwhmA            FLOAT    NOT NULL,
    fwhmB            FLOAT    NOT NULL,
    fwhmTheta        FLOAT    NOT NULL,
    flux             DOUBLE   NOT NULL,
    fluxErr          DOUBLE   NOT NULL,
    psfMag           DOUBLE   NOT NULL,
    psfMagErr        DOUBLE   NOT NULL,
    apMag            DOUBLE   NOT NULL,
    apMagErr         DOUBLE   NOT NULL,
    modelMag         DOUBLE   NOT NULL,
    modelMagErr      DOUBLE   NOT NULL,
    apDia            FLOAT(0)     NULL,
    Ixx              FLOAT(0)     NULL,
    IxxErr           FLOAT(0)     NULL,
    Iyy              FLOAT(0)     NULL,
    IyyErr           FLOAT(0)     NULL,
    Ixy              FLOAT(0)     NULL,
    IxyErr           FLOAT(0)     NULL,
    snr              FLOAT(0) NOT NULL,
    chi2             FLOAT(0) NOT NULL,
    flag4association SMALLINT     NULL,
    flag4detection   SMALLINT     NULL,
    flag4wcs         SMALLINT     NULL,
    _dataSource      SMALLINT NOT NULL
) ENGINE=MyISAM;


